version: '3'

services:
  api:
    build: .

    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3308:3306"
    command: --max_allowed_packet=32505856
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger_database
      MYSQL_USER: messenger_user
      MYSQL_PASSWORD: password